services:
  _defaults:
    autowire:       true
    autoconfigure:  true
    public:         true

##### List Mapper
  Austral\ListBundle\Mapper\ListMapper: "@austral.list.mapper"
  austral.list.mapper:
    class:        Austral\ListBundle\Mapper\ListMapper
    arguments:    ["@router", '@event_dispatcher', "@translator"]

##### Event Subscriber
  austral.list.event_subscriber:
    class:          Austral\ListBundle\EventSubscriber\ListSubscriber
    tags:
      - { name: kernel.event_subscriber }